### ISSUE TITLE
Provide a high-level testing script

### ISSUE THREAD

**Issue by dwinter** [EpistasisLab/regens#12]
This relates to my JOSS review openjournals/joss-reviews#2743

`regens` contains a number of tests, spread across a few different working directories. At present, there is no clear instruction on how to run each test. In the least, it would be helpful to have 

   - [ ] A high-level script for calling tests without needing to move from one subdirectory to another (perhaps defaulting to running all tests)
   - [ ] A README section clearly explaining how to run tests, and what each test is checking

The JOSS review guide says that software is strongly encouraged to include an automated test site, and that a good package will include 'An automated test suite hooked up to an external service such as Travis-CI or similar'. It would be much easier to move to an automated testing service if the current tests were translated into a python testing environment (e.g. `pytest` ,`nose` etc etc). If you chose to move the code to a standard package format for #1, the tests could be included in that structure and run automatically when the package is built.

**Comment by greggj2016** [comment]
commits related to the testing README are below:

https://github.com/EpistasisLab/regens/commit/4b5a4af2a8712ca61c61a700ca81151c99750f3f
https://github.com/EpistasisLab/regens/commit/84eebe3807bfaacd078f90597ec5be728782398d
https://github.com/EpistasisLab/regens/commit/46526aa4dcc8b9b81a392f5ec82c541ceea1d264
https://github.com/EpistasisLab/regens/commit/6d64a9a29f16d949611cbb18d6711d9e52c12f75
https://github.com/EpistasisLab/regens/commit/84bfe457ea44388186f30ee3f90063abb8adc29b

**Comment by greggj2016** [comment]
commits related to the high-level script are below:

https://github.com/EpistasisLab/regens/commit/6b5c15a367d32fe44beb51ba1481485de4b4c296
https://github.com/EpistasisLab/regens/commit/6502a4e3d3b606ee833993bc2529c09f9b83dc17 (this one is most recent)
