### ISSUE TITLE
Clarify recombination map files

### ISSUE THREAD

**Issue by dwinter** [EpistasisLab/regens#13]
As discussed in openjournals/joss-reviews#2743, in the README 

- [ ] Clarify that human recombination maps are included with teh code, so many users will not need to worry about the file format for these
- [ ] Detail the format for users that will need to make a custom one

**Comment by greggj2016** [comment]
Thank you for your detailed review! I'll start addressing both of your suggestions tomorrow.

Just a note about issue #13: your first comment is addressed under the README file's "Input " section, and your second comment is addressed under the "Simulate genotype data with custom recombination rate dataframes" section. It would help me if you could clarify how I might make those sections more visible or simpler to understand.

**Comment by dwinter** [comment]
Just extending this with some points from our discussion openjournals/joss-reviews#2743. 

I think the most important thing is that users know you provide maps for a lot of human populations (the hapmap ones, I think?), and they can be called from the regens commandline easily.

The second thing is to make it clear to a user that they can provide custom maps, and how they could provide them. The README section you have already covers this, though I would consider moving the example input closer to the top of the section. If this format is defined elsewhere (it looks like the first and third column of a `shapeit` map, for instance) you could also link to the definition.

**Comment by greggj2016** [comment]
I have addressed both comments in the following commit:

https://github.com/EpistasisLab/regens/pull/18/commits/bb75edf59b530050e2abfb9387dc9be4afa627c2

This commit is labeled `Update README.md` in this merge:

https://github.com/EpistasisLab/regens/pull/18

**Comment by greggj2016** [comment]
I put a link to the example input in the input description. 

I also put a link to the input description in the input example:

https://github.com/EpistasisLab/regens/commit/fc8a4009b39e7fb5e1363a43603e1dd9c4e73b7b

The tables are output from the [pyrho algorithm](https://github.com/popgenmethods/pyrho), and I can't say with any certainty if they follow a particular format, but I do mention this algorithm a few times.
